server:
  port: 8099

logging:
  path: logs/
  level:
    root: INFO

spring:
  profiles.active: mysql,dev
  messages:
    basename: cn/tendata/mdcs/messages,cn/tendata/mdcs/web/messages,i18n/admin/ValidationMessages
  jpa:
     open-in-view: true
     show-sql: true
     properties:
       jadira.usertype.autoRegisterUserTypes: true
     hibernate:
       naming:
           implicit-strategy: cn.xinbee.rcs.data.jpa.config.CustomImplicitNamingStrategy
       ddl-auto: validate
security:
  ignored: /favicon.ico,css/**,/js/**,/fonts/**,/img/**,/webjars/**,/admin/app/**,/admin/assets/**,/admin/css/**,/admin/html/**,/admin/images/**

multipart:
  enabled: true
  max-file-size: 1Mb
  max-request-size: 10Mb

link:
  accounts.root: ${accounts.server.name:http://localhost:8080/accounts}
  wmt.root: ${wmt.server.name:http://localhost:8080/wmt}
  contactx.root: ${cx.server.name:http://localhost:8080/contactx}
  channel.node.root: ${channel.node.access.properties.uri:http://localhost:8091/api/xinbee/channel/{channelId}/node}
  channel.info.root: ${channel.node.info.uri:http://localhost:8091/api/xinbee/channel/{channelId}}
  rcs.root: ${rcs.server.name:http://localhost:8092}


---
spring:
  profiles: cas
cas:
  service: ${edm.server.name:http://localhost:${server.port}}/login/cas
  server-url-prefix: ${cas.server.name:http://192.168.0.100:8080/cas}
  server-login-url:  ${cas.server-url-prefix}/login
  server-logout-url:  ${cas.server-url-prefix}/logout
  application-parameters.applicationId: 1006
  application-parameters.hasChildUsers: true
---
spring:
  profiles: mysql
  datasource:
    driver-class-name: ${datasource.driver-class-name:com.mysql.jdbc.Driver}
    url: ${datasource.url:jdbc:mysql://192.168.1.111:3306/xinbee_channel}
    username: ${datasource.username:root}
    password: ${datasource.password:}
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
flyway:
  locations: classpath:db/migration/mysql

